# Generated by Django 3.2.9 on 2021-11-29 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empid', models.CharField(max_length=15, unique=True)),
                ('name', models.CharField(max_length=250)),
                ('address', models.CharField(blank=True, max_length=600, null=True)),
                ('salary_perday', models.PositiveIntegerField()),
                ('emp_type', models.CharField(choices=[('ADMIN', 'ADMIN'), ('HR', 'HR'), ('EMPLOYEE', 'EMPLOYEE')], max_length=10)),
                ('email', models.EmailField(blank=True, max_length=250, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
    ]
