# Generated by Django 3.2.9 on 2021-11-30 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='phone',
            field=models.CharField(blank=True, default='+91', max_length=15),
        ),
    ]
