# Generated by Django 3.2.9 on 2021-11-30 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0003_alter_emp_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='email',
            field=models.EmailField(blank=True, default='vedha@gmail.com', max_length=250),
            preserve_default=False,
        ),
    ]
