# Generated by Django 3.2.9 on 2021-11-30 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0005_alter_emp_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='salary_perday',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
